version: '2'
services:
  web:
    depends_on:
      - db
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./www:/code
        - ./config/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
      image: php:7-fpm
      volumes:
          - ./www:/code
      environment:
        WEDDING_API_URL: http://192.168.99.100
  db:
    build: Dockerfiles/mysql
    image: mysql:5.7
    restart: always
    volumes:
       - ./tmp/db_data:/var/lib/mysql
    command: ["--ignore-db-dir=lost+found", "--innodb_use_native_aio=0"]
    environment:
      MYSQL_ROOT_PASSWORD: wp_project
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wp_project
    networks:
      - back
networks:
  back:
volumes:
  db_data: